options:
  fqdn:                       
    type: string               
    description: Fqdn of mattermost server to use
  port:
    type: int
    description: Nginx listen port
    default: 80
    
