options:
  fqdn:                       
    type: string               
    description: |
      FQDN of documize server (for nginx config), defaults to "_"
    default: "_"
  port:
    type: int
    description: Nginx listen port
    default: 80
    
